name: Environment Variables Demo
on: workflow_dispatch
env:
  GLOBAL_ENV: "global-value"
jobs: 
  test-env-vars:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Print global environment variable
        env:
          API_URL: ${{vars.API_URL}}
          API_MODE: ${{vars.API_MODE}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: |
          echo "URL Variable: $API_URL"
          echo "MODE Variable: $API_MODE"
          echo "DB_PASSWORD Variable: $DB_PASSWORD"
          echo "Length of DB_PASSWORD: ${#DB_PASSWORD}"


  demo:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "job-value"

    steps:
      - name: Print all env vars
        run: |
          echo "Global Environment Variable: $GLOBAL_ENV"
          echo "Job Environment Variable: $JOB_ENV"

      - name: Set step environment variable
        env:
          STEP_ENV: "step-value"  
        run: |
          echo "Step Environment Variable: $STEP_ENV"
          echo "Accessing Global Environment Variable in Step: $GLOBAL_ENV"
          echo "Accessing Job Environment Variable in Step: $JOB_ENV"
        
